feat: Enable artifact support for Terraform plan files
Enable supporting the handling of Terraform execution plans as artifacts
within the GitHub Workflows. Specifically, the Plan workflow can create
the terraform.tfplan file, encrypt it with GPG (to protect any secrets
contained therein), and then upload it.

The Apply workflow can download it, and then run Terraform as needed to
deploy the required changes. This allows the building of multi-job
workflows and manage dependencies between them.

diff --git a/.github/workflows/apply.yaml b/.github/workflows/apply.yaml
--- a/.github/workflows/apply.yaml
+++ b/.github/workflows/apply.yaml
@@ -17,31 +17,40 @@ on:
         type: string
         required: true
 
+      artifact-run-id:
+        description: >-
+          The GitHub Actions Run ID for the GitHub Workflow which created a Terraform execution plan to be executed by
+          this workflow.
+        type: string
+        required: true
+      artifact-id:
+        description: >-
+          The ID of the artifact uploaded to GitHub containing the encrypted Terraform execution plan to be executed by
+          this workflow.
+        type: string
+        required: true
+
+      # GCP credentials are always required as GCS manages the storage and locking for the Terraform state file.
+
       gcp-project-id:
         description: >-
           The GCP Project ID to use both for authenticating to GCP for Terraform, and as the default Project to deploy
-          to for any Terraform resources (or to query from for data sources). This is only required if there is a Google
-          provider configured in the Terraform configuration.
+          to for any Terraform resources (or to query from for data sources).
         type: string
-        required: false
-        default: ""
+        required: true
       gcp-workload-identity-provider:
         description: >-
-          The GCP Workload Identity Provider to use for authenticating to GCP for Terraform. This is only required if
-          there is a Google provider configured in the Terraform configuration.
+          The GCP Workload Identity Provider to use for authenticating to GCP for Terraform.
         type: string
-        required: false
-        default: ""
+        required: true
       gcp-service-account-email:
         description: >-
           The email address for the GCP Service Account to impersonate when authenticating to GCP for Terraform
           (although any GCP Service Account specified by the `impersonate_service_account` block in any of the GCP
           Terraform provider block will override this value, assuming this Service Account has permissions to
-          impersonate the configured `impersonate_service_account`). This is only required if there is a Google provider
-          configured in the Terraform configuration.
+          impersonate the configured `impersonate_service_account`).
         type: string
-        required: false
-        default: ""
+        required: true
 
       aws-region:
         description: >-
@@ -101,6 +110,12 @@ on:
         default: ""
 
     secrets:
+      TF_PLAN_PASSPHRASE:
+        description: >-
+          The passphrase to use for decrypting the Terraform execution plan, as generated by a previous `plan` GitHub
+          Workflow job artifact.
+        required: true
+
       TS_OAUTH_CLIENT_ID:
         description: >-
           The Tailscale OAuth Client ID to use for authenticating to Tailscale with the GitHub Actions runner to allow
@@ -178,6 +193,45 @@ jobs:
           path: ~/.terraform.d/plugin-cache
           key: terraform-${{ runner.os }}-${{ hashFiles(format('{0}/{1}', inputs.configuration, 'terraform.tf')) }}
 
+      - name: Retrieve the Terraform execution plan
+        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        with:
+          run-id: ${{ inputs.artifact-run-id }}
+          artifact-ids: ${{ inputs.artifact-id }}
+          digest-mismatch: error
+          skip-decompress: true
+
+      - name: Decrypt and extract the Terraform execution plan
+        env:
+          TF_CONFIGURATION: ${{ inputs.configuration }}
+          TF_PLAN_PASSPHRASE: ${{ secrets.TF_PLAN_PASSPHRASE }}
+        run: |-
+          # gpg --decrypt terraform.tfplan.tgz.gpg && tar ...
+
+          if [[ ! -f "terraform.tfplan.tgz.gpg" ]]; then
+            echo "::error title=gpg --decrypt terraform.tfplan.tgz.gpg::No encrypted copy of the Terraform" \
+              "execution plan was found when preparing to decrypt the artifact."
+            exit 1
+          elif [[ -z "${TF_PLAN_PASSPHRASE}" ]]; then
+            echo "::error title=gpg --decrypt terraform.tfplan.tgz.gpg::The encrypted copy of the Terraform" \
+              "execution plan is present, but the passphrase to decrypt the file is not set."
+            exit 1
+          fi
+
+          echo "::group::Decrypt terraform.tfplan.tgz.gpg"
+          PASS=$(mktemp "${GITHUB_WORKSPACE}/.tfplan-passphrase-XXXXXXXXXX")
+          echo -n "${TF_PLAN_PASSPHRASE}" > "${PASS}"
+
+          gpg  --pinentry-mode loopback --batch --decrypt --passphrase-file "${PASS}" \
+            --yes --output 'terraform.tfplan.tgz' 'terraform.tfplan.tgz.gpg'
+          shred --force --remove --zero "${PASS}"
+          echo "::endgroup::"
+
+          echo "::group::Extract terraform.tfplan.tgz"
+          tar --extract --gzip --verbose --file 'terraform.tfplan.tgz'
+          shred --force --remove --zero 'terraform.tfplan.tgz' 'terraform.tfplan.tgz.gpg'
+          echo "::endgroup::"
+
       - name: Connect to the Tailscale network
         id: tailscale
         if: env.TS_OAUTH_CLIENT_ID != '' && env.TS_AUDIENCE != ''
@@ -239,10 +293,6 @@ jobs:
           # We do not need this GitHub Action to do anything with the Vault instance, we just need it to authenticate
           # and provide the Vault token to Terraform. Therefore, we set it to export the Vault token only.
           exportToken: true
-
-      # TODO: Fetch the Terraform execution plan file (i.e. terraform.tfplan) from the `plan` workflow and use it here
-      #       to apply the changes, rather than re-running the plan here. This should also be configurable to allow
-      #       this workflow to run independently of the `plan` workflow, and generate its own plan file to apply.
 
       - name: Force DNS to the Tailscale network
         if: env.TS_OAUTH_CLIENT_ID != '' && env.TS_AUDIENCE != ''
diff --git a/.github/workflows/plan.yaml b/.github/workflows/plan.yaml
--- a/.github/workflows/plan.yaml
+++ b/.github/workflows/plan.yaml
@@ -17,31 +17,27 @@ on:
         type: string
         required: true
 
+      # GCP credentials are always required as GCS manages the storage and locking for the Terraform state file.
+
       gcp-project-id:
         description: >-
           The GCP Project ID to use both for authenticating to GCP for Terraform, and as the default Project to deploy
-          to for any Terraform resources (or to query from for data sources). This is only required if there is a Google
-          provider configured in the Terraform configuration.
+          to for any Terraform resources (or to query from for data sources).
         type: string
-        required: false
-        default: ""
+        required: true
       gcp-workload-identity-provider:
         description: >-
-          The GCP Workload Identity Provider to use for authenticating to GCP for Terraform. This is only required if
-          there is a Google provider configured in the Terraform configuration.
+          The GCP Workload Identity Provider to use for authenticating to GCP for Terraform.
         type: string
-        required: false
-        default: ""
+        required: true
       gcp-service-account-email:
         description: >-
           The email address for the GCP Service Account to impersonate when authenticating to GCP for Terraform
           (although any GCP Service Account specified by the `impersonate_service_account` block in any of the GCP
           Terraform provider block will override this value, assuming this Service Account has permissions to
-          impersonate the configured `impersonate_service_account`). This is only required if there is a Google provider
-          configured in the Terraform configuration.
+          impersonate the configured `impersonate_service_account`).
         type: string
-        required: false
-        default: ""
+        required: true
 
       aws-region:
         description: >-
@@ -100,7 +96,29 @@ on:
         required: false
         default: ""
 
+    outputs:
+      artifact-run-id:
+        description: >-
+          The GitHub Actions Run ID for the GitHub Workflow that created the Terraform execution plan, which can be used
+          by subsequent jobs to fetch the artifact for applying the configuration changes.
+        value: ${{ jobs.plan.outputs.artifact-run-id }}
+      artifact-id:
+        description: >-
+          The ID of the GitHub Artifact uploaded that contains the encrypted Terraform execution plan, which can be used
+          by subsequent jobs to fetch and applying the configuration changes.
+        value: ${{ jobs.plan.outputs.artifact-id }}
+      artifact-digest:
+        description: >-
+          The SHA256 digest of the GitHub Artifact uploaded that contains the encrypted Terraform execution plan, which
+          can be used to verify the integrity of the artifact before applying the configuration changes.
+        value: ${{ jobs.plan.outputs.artifact-digest }}
+
     secrets:
+      TF_PLAN_PASSPHRASE:
+        description: >-
+          The passphrase to use for encrypting the Terraform execution plan, as generated by this GitHub Workflow.
+        required: true
+
       TS_OAUTH_CLIENT_ID:
         description: >-
           The Tailscale OAuth Client ID to use for authenticating to Tailscale with the GitHub Actions runner to allow
@@ -163,6 +181,10 @@ jobs:
       id-token: write # request GitHub OIDC tokens to submit to multiple providers
       issues: write # submit or change comment on a Pull Request
       pull-requests: write # make changes to the Pull Request
+    outputs:
+      artifact-run-id: ${{ github.run_id }}
+      artifact-id: ${{ steps.upload.outputs.artifact-id }}
+      artifact-digest: ${{ steps.upload.outputs.artifact-digest }}
 
     steps:
       - name: Checkout the repository
@@ -274,5 +296,44 @@ jobs:
           # resolvectl default-route eth0 yes
           sudo resolvectl default-route eth0 yes
 
-      # TODO: Upload the Terraform execution plan file (i.e. terraform.tfplan) for the `apply` workflow so it can be
-      #       used to apply the changes, rather than re-running the plan again.
+      - name: Archive and encrypt the Terraform execution plan
+        env:
+          TF_CONFIGURATION: ${{ inputs.configuration }}
+          TF_PLAN_PASSPHRASE: ${{ secrets.TF_PLAN_PASSPHRASE }}
+        run: |-
+          # tar ... && gpg --symmetric terraform.tfplan.tgz
+
+          if [[ ! -f "${TF_CONFIGURATION}/terraform.tfplan" ]]; then
+            echo "::error title=gpg --symmetric ${TF_CONFIGURATION}/terraform.tfplan::No Terraform execution plan was" \
+              "found when preparing to encrypt the artifact."
+            exit 1
+          elif [[ -z "${TF_PLAN_PASSPHRASE}" ]]; then
+            echo "::error title=gpg --symmetric ${TF_CONFIGURATION}/terraform.tfplan::The Terraform execution plan is" \
+              "present, but the passphrase to encrypt the file is not set."
+            exit 1
+          fi
+
+          echo "::group::Create terraform.tfplan.tgz"
+          tar --create --gzip --verbose --file 'terraform.tfplan.tgz' \
+            "${TF_CONFIGURATION}/terraform.tfplan" "${TF_CONFIGURATION}/.terraform" .task/checksum/*
+          shred --force --remove --zero "${TF_CONFIGURATION}/terraform.tfplan"
+          echo "::endgroup::"
+
+          echo "::group::Encrypt terraform.tfplan.tgz"
+          PASS=$(mktemp "${GITHUB_WORKSPACE}/.tfplan-passphrase-XXXXXXXXXX")
+          echo -n "${TF_PLAN_PASSPHRASE}" > "${PASS}"
+
+          gpg --pinentry-mode loopback --batch --symmetric --cipher-algo AES256 --passphrase-file "${PASS}" \
+            --yes --output 'terraform.tfplan.tgz.gpg' 'terraform.tfplan.tgz'
+          shred --force --remove --zero "${PASS}"
+          echo "::endgroup::"
+
+      - name: Upload the Terraform execution plan
+        id: upload
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+        with:
+          name: ${{ inputs.configuration }}:${{ inputs.environment }}:terraform.tfplan.gpg
+          path: terraform.tfplan.tgz.gpg
+          if-no-files-found: error
+          overwrite: true
+          archive: false
